### ISSUE TITLE
Port Peloton Plan Node Code

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#137]
We need to bring over the plan node classes from Peloton into the new repo:

https://github.com/cmu-db/peloton/tree/master/src/include/planner

There are some fixes that we need to do with the original code:

1. Remove all pointers to database objects (e.g., `DataTable`). Everything should be replaced with object identifiers.

2. Replace `SerializeTo` and `DeserializeFrom` with the new JSON serialization code.
https://github.com/cmu-db/peloton/blob/master/src/include/planner/abstract_plan.h#L123

3. Ideally I would like to rename all of the objects from `*Plan` to `*PlanNode`, but I am open for discussion about this.

4. We should comment out the `PerformBinding` and `VisitParameters` methods for now.

5. We are also going to have to bring in the Expression code. We should clean this up to remove the dependency on the old value type system. We should discuss this with @pmenon to find out what needs.

**Comment by lmwnshn** [comment]
Might be a good time to figure out wiki glossary / agree on what an object identifier is. @tli2 @mbutrovich

**Comment by tli2** [comment]
Postgres sort of just say "oh it's whatever we use for primary key in a systems table". I think it makes sense that `oid_t`'s definition be somewhat related to the Catalog.

**Comment by lmwnshn** [comment]
Just throwing some stuff for Tuesday here.

Some blocking stuff:
- enums
- PerformBinding/BindingContext design as per #114 - still thinking about it. I agree that there should be a better way.
- and expressions as mentioned above, though that can be stubbed

Less important, refactorable:
- directory structure, do I get a "planning" folder in include and src?
- will binding/creation of plan nodes ever happen from multiple writer threads? May be related to old peloton bug
- node cardinality - who calculates it? will it be updated? where is it stored?
- debug logging - log what and under which module?

I'm also retyping the stuff and stripping things out as I go along. For example, I don't think it makes sense to have a name attribute in AttributeInfo while saying "you can't count on the name being there all the time".

But blocking stuff aside, otherwise looks like a relatively clean port, modulo some stubbing. If we clear the blocking stuff, I think I can hope to get most of the plan node types in by next Sunday.

**Comment by wenxuanqiu** [comment]
Individual plan nodes should look like `<PlanNodeName>(Schema, <other, arguments>)`, catalog::Schema will replace the existing attribute info and project info

**Comment by pervazea** [comment]
catalog::Schema looks like it works, but...
catalog::Schema, as used by the storage layer, contains a specification of all the columns in the table.
For the plans though, my recollection is that plan nodes do not have to materialize or pass through all the columns. A plan may pass back a single column out of many.

It is going to be confusing, when reading the code, if it is a full schema specification or a partial one.  I think we'll want to differentiate the two, for maintainability, even if the underlying class is the same.

**Comment by tli2** [comment]
fixed by #312
