### ISSUE TITLE
Webhook triggering Jenkins builds on all open PRs and master

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#193]
It seems like when a PR finishes its Travis build and triggers the web hook on Jenkins, that causes a rebuild of every open PR and the master branch. In this case, it looks like #192 finished Travis triggered all of these builds:

![screen shot 2018-10-04 at 4 52 43 pm](https://user-images.githubusercontent.com/6855576/46502399-13a0fd00-c7f6-11e8-90e8-a4f355d3c16b.png)

**Comment by mbutrovich** [comment]
#200 that I opened yesterday isn't running Jenkins at all :(

**Comment by crd477** [comment]
#200 ran because I manually did "Scan Repository Now" just to make sure that it would be picked up that way.  I still have to figure out how instruct the webhook to provide appropriate information about what should be built.  Fundamentally, it's the same problem as how to ensure that lots of builds in other branches don't get triggered for every PR.

**Comment by mbutrovich** [comment]
Closed by #214
