### ISSUE TITLE
Improve serialization of delta records

### ISSUE THREAD

**Issue by swimj** [cmu-db/terrier#262]
This is issue is related to both the correctness and performance of logging.  

Currently, we do a direct dump of the in-memory delta record (i.e. a ProjectedRow) to the log file on disk.  This was so we could get some basic logging infrastructure set up in the system, but was never the right thing to do.

Writing out the raw ProjectedRow has at least 2 problems:
- [x] (1) Log file does not store enough information to replay changes made to fields that use a varlen pool for storage.  This is because the value in the ProjectedRow is only a pointer to the varlen entry.  The log manager writes out the pointer instead of the actual contents of the delta. ~~ 

It will take some work to actually support this functionality (not just change a few lines), because by dumping out the entire delta, the log manager currently doesn't get its hands dirty with the details of ProjectedRow.  To differentiate between inline/varlen attributes, the log manager should at least have to iterate over the projection list.

- [x] (2) Writing out the entire in-memory ProjectedRow is inefficient.  For example, a ProjectedRow needs to have space for all attributes in the projection list, whether or not those attributes are actually null or not.  There is no need to write out the data corresponding to the "value" of a column that is actually null, but we currently do this because the size of a ProjectedRow only depends on the BlockLayout and projection list, and not on whether any of the columns happen to be null.  As another example, a ProjectedRow may have padding so that accesses at runtime are well-aligned. There's no reason for the log to keep this padding.

**Comment by tli2** [comment]
Partially fixed by #370

**Comment by GustavoAngulo** [comment]
@tli2 I believe #370 also addressed the second point. You can see in this code we skip over null attributes. We're able to do this because we also serialize out the null bitmap.
https://github.com/cmu-db/terrier/blob/6b1d5aaedaa3d4d8cb17b7e61b8397df2a185c2a/src/storage/write_ahead_log/log_serializer_task.cpp#L121-L126
And in this code, we only write out the value without padding:
https://github.com/cmu-db/terrier/blob/6b1d5aaedaa3d4d8cb17b7e61b8397df2a185c2a/src/storage/write_ahead_log/log_serializer_task.cpp#L143-L146
