### ISSUE TITLE
Segfault in catalog branch

### ISSUE THREAD

**Issue by lagoon0o0** [cmu-db/terrier#339]
When we are implementing the Add/Drop Index, see PR #337, we came across an issue that causes the failure of `catalog_test`. The bug occurs when `Catalog::Dump` calls the `AttributeHandle::Dump` and finally calls the `SqlTableRW::Dump`. And a segfault happens during scanning the table.
To reproduce the bug, you can run `catalog_test` on commit：[6a6917c63aff65b46c947e14db3fc453a663fa67](https://github.com/cmu-db/terrier/tree/6a6917c63aff65b46c947e14db3fc453a663fa67).

The issue disappears if we decrease the number of elements in PGAttribute, see commit: [8ae9c26caae6166a5ee24cb936baf0acf3b01420](https://github.com/cmu-db/terrier/tree/8ae9c26caae6166a5ee24cb936baf0acf3b01420)

The error information is as follows:
<img width="1276" alt="error_msg" src="https://user-images.githubusercontent.com/9077712/55697971-c878ca00-5991-11e9-98aa-a254b7f6f659.png">

Thanks!

**Comment by pervazea** [comment]
In the scenario reproduced so far:
- add items to pg_attribute
- delete an item from pg_attribute
- do a scan. Traversing the version pointer segfaults.

In more detail:
DataTable::Delete
.... txn->StageDelete(this, slot)

get a redo buffer
byte *RedoBuffer::NewEntry(const uint32_t size) {
  if (buffer_seg_ == nullptr) {
    // this is the first write
 ===>   buffer_seg_ = buffer_pool_->Get();
  } else if (!buffer_seg_->HasBytesLeft(size)) {
    // old log buffer is full
    if (log_manager_ != LOGGING_DISABLED)
      log_manager_->AddBufferToFlushQueue(buffer_seg_);

now initialize it...
  static LogRecord *InitializeHeader(byte *const head, const LogRecordType type, const uint32_t size,
                                     const transaction::timestamp_t txn_begin) {
    auto *result = reinterpret_cast<LogRecord *>(head);
    ===> result->type_ = type;
    result->size_ = size;
    result->txn_begin_ = txn_begin;

result = 0x55df18b11120, and type = 2 (a LogRecordType::DELETE)

Then, in DataTable::SelectIntoBuffer...line 248
version_ptr = 0x55df18b11120
    UndoRecord *next_ver = version_ptr->Next();
and Next() returns 2 (i.e. the type of a DELETE record rather than a valid next ptr)

**Comment by mbutrovich** [comment]
Here's what I believe is happening based on looking at the code. I haven't stepped through it with a debugger yet but it seems to check out:

Catalog::Bootstrap starts a transaction, populates the catalog tables, and commits. At the end of the function on [line 175 it then deletes the TransactionContext](https://github.com/cmu-db/terrier/blob/6a6917c63aff65b46c947e14db3fc453a663fa67/src/catalog/catalog.cpp#L175). This is unsafe because the DataTable is still going to have pointers into the transaction's UndoBuffer, but the TransactionContext destructor is going to release all of the UndoBuffer's RecordBufferSegments back to the pool, which are then reused for the next transaction which fills them with garbage. The result is DataTable's version vectors pointing into UndoRecords that have probably been clobbered with garbage data, which results in data corruption and/or segfaults when you access the DataTable.

Moral of the story: if you're gonna roll without GC (as the current catalog tests are) then you better be really sure a TransactionContext can be deleted. Since the order of operations we defined on the whiteboard yesterday show the GC being started before the catalog in main, the catalog should probably be written to assume a running GC and _never_ manually delete a TransactionContext.

**Comment by pervazea** [comment]
This has overlap with the issue #323.
A quick fix (that works) is to modify Bootstrap to take in a transaction, rather than creating its own.

The real fix is the one for issue #323. Removing the use of shared ptrs to tables in the catalog code and controlling when and how the data tables are deleted. This is more than the quick fix above.

**Comment by tli2** [comment]
Is this fixed?

**Comment by pervazea** [comment]
Yes, there is a fix in the catalog PR for this.

We are going to go from using shared ptrs to raw pointers for tables, and adjust some of the code accordingly, for the long term fix.  TBD whether that is part of the current catalog PR or a follow on.



________________________________
