### ISSUE TITLE
Jenkins failure to check out from git

### ISSUE THREAD

**Issue by tli2** [cmu-db/terrier#353]
Example:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-324/35/pipeline/10
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/master/217/pipeline/13

This has been going on since the weekends, and seems to fail for certain jobs. However, some PR somehow got through just fine. @crd477 Any idea what might be causing this?

**Comment by crd477** [comment]
This happens periodically and seems to be caused by the swarm agent on only a few of the workers losing some state with the swarm controller.  Restarting the agents fixed the problem.  I suspect this problem is related to an update and restart of the Jenkins controller without restarting all of the swarm agents, even though it's supposed to be a safe operation.  I'll try to verify that theory the next time an update is released.

I looked back through the list of recent build failures and restarted those that were affected by this.  If you think I missed any, please let me know and I'll replay those as well.

**Comment by tli2** [comment]
Thanks a lot!
