### ISSUE TITLE
Trigger Jenkins build on successful Travis run

### ISSUE THREAD

**Issue by mbutrovich** [cmu-db/terrier#534]
Right now I believe Jenkins polls for any PRs to run. Ideally we'd like Jenkins to only be triggered when Travis passes. Hopefully there are Travis triggers and Jenkins APIs to make this possible.

**Comment by crd477** [comment]
I remember that we tried this before in #183.  That attempt failed and I backed it out because it only used a single, static trigger.  Once that Jenkinsfile got merged into master and other users eventually rebased their working branches, every commit they made to those branches would cause an explosion of build requests in unrelated branches, like open PRs to upstream, upstream master, and everywhere in between.

I'm happy to revisit this but it will take me a little while to understand how to do it correctly in order to avoid the disaster that resulted last time.

**Comment by mbutrovich** [comment]
Takeaway from yesterday's discussion: @crd477 will instead explore a multi-stage Jenkins pipeline and we'll ditch Travis entirely.

**Comment by crd477** [comment]
I don't know if we settled on what the initial pass/fail stage would look like in terms of build steps and environment.  Could you describe that or point me to a Travis stage that I should use as a model?

**Comment by mbutrovich** [comment]
I think the travis.yml in the repo is a good place for us to start for the first stage. On all systems it runs:
```
make
make check-format
make check-lint
make check-censored
```
That seems like a good first stage. The second stage could be the Jenkins pipeline we have now.

A theoretical third stage would be a scalability test on a beefy EC2 box if everything else passes, but we don't have the infrastructure for that yet.

**Comment by crd477** [comment]
Sorry for the delay in getting back to this.  Does the "shape" depicted [here](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/crd%2Fterrier-crd/detail/benchstage/10/pipeline) match the goal?
This is just a mocked up example but if it's right in principle, I'll submit the actual change.

**Comment by apavlo** [comment]
Yes, this looks like what we want.
