### ISSUE TITLE
ExecEngine should use STRONG_TYPEDEF(col_id_t)

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#663]
The execution engine uses `uint16_t` to pass around column offsets into projected columns:

https://github.com/cmu-db/terrier/blob/master/src/include/execution/vm/bytecode_handlers.h#L282

To match other parts of the system, it should use our typedef `col_id_t` to make it clear what the value represents:

https://github.com/cmu-db/terrier/blob/master/src/include/storage/storage_defs.h#L32

**Comment by wgy8283335** [comment]
Hi, I'd like to take care of it. @apavlo

**Comment by turingcompl33t** [comment]
Closing this issue with a won't fix for the following reasons:
- `ProjectedColumnsIterator`, the original target of this issue, no longer exists.
- The remaining instances of use of `uint16_t` to index into `ProjectedRows` with `ProjectedRow::Get()` and `ProjectedRow::Set()` refer to a column index rather than a storage layer column ID, thus it would be inappropriate to represented these indicies with the `col_id_t` type.
