### ISSUE TITLE
Move Limit/Offset Fields to AbstractScanPlanNode

### ISSUE THREAD

**Issue by apavlo** [cmu-db/terrier#936]
`IndexScanPlanNode` has a single field to support limits:

https://github.com/cmu-db/terrier/blob/master/src/include/planner/plannodes/index_scan_plan_node.h#L236

There is no reason that we should have the same field in `SeqScanPlanNode`. Therefore, we should move it into `AbstractScanPlanNode`.

Furthermore, we should also add the `offset` field with the limit to have the same semantics as `LimitPlanNode`.

**Comment by jkosh44** [comment]
Can I try this one out?

**Comment by apavlo** [comment]
@jkosh44 Yes!

**Comment by jkosh44** [comment]
Cool, I'm hoping it'll help me get a better understanding of the code base, C++, and CLion.

I have a couple of quick questions/notes
1. Just wanted to note that adding these two fields to `AbstractScanPlanNode` will add them to `CSVScanPlanNode` as well since it's not mentioned in the issue.
2. For the constructors should we
  a. Create new constructors with limit and offset and initialize these to some default/null in the old constructors?
or
  b. Modify existing constructors?
3. In CLion what executable am I supposed to pick when running a CMake goal (I'm new to CMake and wasn't able to find this in the wiki)?

**Comment by apavlo** [comment]
1. Adding them to `AbstractScanPlanNode` automatically adds them to `CSVScanPlanNode`.
2. You have to add the fields to the builder classes and then modify the existing constructors.
3. Cmake goal = `terrier` binary

**Comment by jkosh44** [comment]
Closing because https://github.com/cmu-db/terrier/pull/938 was merged
