### ISSUE TITLE
Remove StrongTypeAlias::operator! in favor of static_cast<>()

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/terrier#951]
The first time I saw stuff like [auto offset = static_cast<uint16_t>(!varlen_col_id - NUM_RESERVED_COLUMNS);](https://github.com/cmu-db/terrier/blob/master/src/storage/block_compactor.cpp#L172), I thought there _had_ to be a typo and kept trying to figure out how it ever worked. It took me about an hour to realize that operator! was defined on StrongTypeAlias and returned the underlying value.

Today, I think that @eppingere and @thepinetree fell into a similar rabbit hole with the timestamp parsing fixes.

Matt even has a warning on his 721 slides.

If we remove [operator!](https://github.com/cmu-db/terrier/blob/master/src/include/common/strong_typedef.h#L95) in favor of a [static_cast<UnderlyingType>](https://github.com/cmu-db/terrier/blob/9741e4d3068af7f80136e4922c1591ba2522cb54/src/traffic_cop/traffic_cop.cpp#L371):

- +: Future people won't have this confusion.
- -: We might have to be more careful when changing the underlying type of the strong typedef (unless clang-tidy catches this?).

**Comment by DreaMer963** [comment]
I also got into this situation...

**Comment by turingcompl33t** [comment]
I started the transition over to `static_cast<>` when that second bullet from the original issue submission became much more salient: if we replace all of the use of `operator!()`  with `static_cast<>` then subsequent changes to the underlying type in the definition of a strong typedef become painful manual refactors because the the specified type at each site at which we need to access the underlying value must change as well. I propose we pursue one of the following alternatives:
- Add a member `underlying_value()` that behaves exactly as `operator!()` does now but succeeds in making the intent more explicit; this is the approach taken by other strong typedef libraries e.g. the one authored by Anthony Williams: https://github.com/anthonywilliams/strong_typedef
- Add a non-member `underlying_value()` that simply determines the underlying type of the strong typedef via partial template specialization and performs a `static_cast<>` to this type; might have a slight impact on compilation time but shouldn't be anything too significant
